# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-08-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoBlog', '0002_project_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[(b'T', b'Text'), (b'P', b'Photo'), (b'H', b'Raw')], max_length=1),
        ),
    ]
