# Generated by Django 2.2.28 on 2024-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoBlog', '0003_auto_20220814_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('P', 'Photo'), ('H', 'Raw')], max_length=1),
        ),
    ]
